name: ms5-ingesta

x-job: &job
  restart: "no"
  environment:
    OUTPUT_DIR: /reports
    AWS_EC2_METADATA_DISABLED: "true"
    INGESTION_RUN_ID: ${INGESTION_RUN_ID:-}
  volumes:
    - ./reports:/reports
  extra_hosts:
    - "host.docker.internal:host-gateway"

services:
  ingesta-ms1:
    <<: *job
    build:
      context: .
      dockerfile: ingesta-ms1/Dockerfile
    env_file:
      - ./aws.env
      - ./ms1.env

  ingesta-ms2:
    <<: *job
    build:
      context: .
      dockerfile: ingesta-ms2/Dockerfile
    env_file:
      - ./aws.env
      - ./ms2.env

  ingesta-ms3:
    <<: *job
    build:
      context: .
      dockerfile: ingesta-ms3/Dockerfile
    env_file:
      - ./aws.env
      - ./ms3.env
