name: ms5-api

services:
  ms5-api-app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - aws.env
      - athena.env
    ports:
      - "8084:8000"
    restart: unless-stopped
